#!/bin/bash

bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=True,return_format=python
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=True,return_format=json
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=True,return_format=verbose_xml
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=True,return_format=concise_xml
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=python
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=json
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=verbose_xml
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=concise_xml
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=True,return_format=python
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=True,return_format=json
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=True,return_format=verbose_xml
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=True,return_format=concise_xml

bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=False,return_format=python
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=False,return_format=json
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=False,return_format=verbose_xml
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=False,return_format=concise_xml
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=python
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=json
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=verbose_xml
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=concise_xml
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=False,return_format=python
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=False,return_format=json
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=False,return_format=verbose_xml
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=False,return_format=concise_xml

bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=python,prompt_format=markdown
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=python,prompt_style=experimental
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=python,prompt_format=markdown
bfcl generate --model Qwen/Qwen3-32B --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=python,prompt_style=experimental

bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=True,return_format=python
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=True,return_format=json
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=True,return_format=verbose_xml
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=True,return_format=concise_xml
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=python
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=json
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=verbose_xml
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=concise_xml
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=True,return_format=python
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=True,return_format=json
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=True,return_format=verbose_xml
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=True,return_format=concise_xml

bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=False,return_format=python
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=False,return_format=json
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=False,return_format=verbose_xml
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=python,has_tool_call_tag=False,return_format=concise_xml
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=python
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=json
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=verbose_xml
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=concise_xml
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=False,return_format=python
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=False,return_format=json
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=False,return_format=verbose_xml
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=xml,has_tool_call_tag=False,return_format=concise_xml

bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=python,prompt_format=markdown
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=True,return_format=python,prompt_style=experimental
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=python,prompt_format=markdown
bfcl generate --model meta-llama/Llama-3.1-70B-Instruct --test-category simple,parallel,multiple,parallel_multiple,live_simple,live_multiple,live_parallel,live_parallel_multiple --prompt-variation function_doc_format=json,has_tool_call_tag=False,return_format=python,prompt_style=experimental